# Generated by Django 4.0.6 on 2022-07-06 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Ваше имя:')),
                ('email', models.CharField(max_length=255, verbose_name='Ваш e-mail:')),
                ('text', models.CharField(max_length=255)),
                ('published_date', models.DateTimeField(verbose_name='дата сообщения')),
            ],
        ),
    ]
