# Generated by Django 4.0.6 on 2022-07-12 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'permissions': (('can_see_messages', 'You can see list messages'),)},
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(max_length=100, verbose_name='Ваш e-mail:'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Ваше имя:'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата сообщения'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='text',
            field=models.TextField(max_length=255, verbose_name='Сообщение'),
        ),
    ]
