# Generated by Django 4.0.6 on 2022-07-13 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_contact_options_alter_contact_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0, verbose_name='Всего посещений сайта')),
            ],
            options={
                'verbose_name': 'Всего посещений сайта',
                'verbose_name_plural': 'Всего посещений сайта',
            },
        ),
    ]
