# Generated by Django 4.0.6 on 2022-07-13 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_visitnumber'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visitnumber',
            options={'verbose_name': 'Всего просмотров резюме', 'verbose_name_plural': 'Всего просмотров резюме'},
        ),
        migrations.AlterField(
            model_name='visitnumber',
            name='count',
            field=models.IntegerField(default=0, verbose_name='Всего просмотров резюме'),
        ),
    ]
