# Generated by Django 4.0.6 on 2022-07-13 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_visitnumber_options_alter_visitnumber_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=30, verbose_name='Айпи адрес')),
                ('count', models.IntegerField(default=0, verbose_name='Визиты')),
            ],
            options={
                'verbose_name': 'Доступ к информации о пользователе',
                'verbose_name_plural': 'Доступ к информации о пользователе',
            },
        ),
    ]
