# Generated by Django 4.0.6 on 2022-07-13 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_userip'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='текст новости')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='дата загрузки с сайта')),
                ('link', models.URLField(max_length=255, verbose_name='URL')),
            ],
        ),
    ]
